package com.skyair.resolutionagent.model;

public enum EscalationReason {
    COMPENSATION_BEYOND_POLICY,
    FARE_DIFFERENCE_ABOVE_LIMIT,
    NON_AIRLINE_DISRUPTION_EXCEPTION,
    LEGAL_THREAT_OR_FORMAL_COMPLAINT,
    REFUND_DIFFERENT_PAYMENT_METHOD,
    FREE_CLASS_UPGRADE_REQUEST,
    FULL_NIGHT_HOTEL_REQUESTED,
    HUMAN_HANDOFF_REQUESTED,
    MEDICAL_EMERGENCY_SPECIAL_ASSISTANCE,
    AGENT_LACKS_AUTHORITY
}
