package com.skyair.resolutionagent.model;

public enum Intent {
    FLIGHT_STATUS,
    CANCELLATION_INFO,
    REFUND_REQUEST,
    REBOOKING_REQUEST,
    MEAL_VOUCHER_REQUEST,
    LOUNGE_ACCESS_REQUEST,
    HOTEL_REQUEST,
    COMPENSATION_REQUEST,
    FARE_DIFFERENCE_WAIVER,
    UPGRADE_REQUEST,
    LEGAL_COMPLAINT,
    HUMAN_AGENT_REQUEST,
    EMERGENCY_MEDICAL_ASSISTANCE,
    GENERAL_INQUIRY,
    UNKNOWN
}
